config/routes.rb
Snikkit::Application.routes.draw do
  get "users/new"

  get "pages/contact"

  get "pages/help"

  get "pages/home"

  get "pages/about"

  resources :snikks

  resources :microposts

  resources :users

  match '/sign-up',  :to => 'users#new'
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'

  root :to => 'pages#home'  

end

app/models/micropost.rb
# == Schema Information
# Schema version: 20110603083722
#
# Table name: microposts
#
#  id         :integer(4)      not null, primary key
#  content    :string(255)
#  url        :string(255)
#  user_id    :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

class Micropost < ActiveRecord::Base
  belongs_to :user
end

app/models/snikk.rb
# == Schema Information
# Schema version: 20110603083722
#
# Table name: snikks
#
#  id         :integer(4)      not null, primary key
#  content    :string(255)
#  url        :string(255)
#  user_id    :integer(4)
#  created_at :datetime
#  updated_at :datetime
#

class Snikk < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
# Schema version: 20110603083722
#
# Table name: users
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
  attr_accessible :name, :email  
  has_many :snikks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  # GET /microposts
  # GET /microposts.xml
  def index
    @microposts = Micropost.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @microposts }
    end
  end

  # GET /microposts/1
  # GET /microposts/1.xml
  def show
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @micropost }
    end
  end

  # GET /microposts/new
  # GET /microposts/new.xml
  def new
    @micropost = Micropost.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @micropost }
    end
  end

  # GET /microposts/1/edit
  def edit
    @micropost = Micropost.find(params[:id])
  end

  # POST /microposts
  # POST /microposts.xml
  def create
    @micropost = Micropost.new(params[:micropost])

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to(@micropost, :notice => 'Micropost was successfully created.') }
        format.xml  { render :xml => @micropost, :status => :created, :location => @micropost }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /microposts/1
  # PUT /microposts/1.xml
  def update
    @micropost = Micropost.find(params[:id])

    respond_to do |format|
      if @micropost.update_attributes(params[:micropost])
        format.html { redirect_to(@micropost, :notice => 'Micropost was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @micropost.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.xml
  def destroy
    @micropost = Micropost.find(params[:id])
    @micropost.destroy

    respond_to do |format|
      format.html { redirect_to(microposts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def about
    @title = "About"
  end

end

app/controllers/snikks_controller.rb
class SnikksController < ApplicationController
  # GET /snikks
  # GET /snikks.xml
  def index
    @snikks = Snikk.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @snikks }
    end
  end

  # GET /snikks/1
  # GET /snikks/1.xml
  def show
    @snikk = Snikk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @snikk }
    end
  end

  # GET /snikks/new
  # GET /snikks/new.xml
  def new
    @snikk = Snikk.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @snikk }
    end
  end

  # GET /snikks/1/edit
  def edit
    @snikk = Snikk.find(params[:id])
  end

  # POST /snikks
  # POST /snikks.xml
  def create
    @snikk = Snikk.new(params[:snikk])

    respond_to do |format|
      if @snikk.save
        format.html { redirect_to(@snikk, :notice => 'Snikk was successfully created.') }
        format.xml  { render :xml => @snikk, :status => :created, :location => @snikk }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @snikk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /snikks/1
  # PUT /snikks/1.xml
  def update
    @snikk = Snikk.find(params[:id])

    respond_to do |format|
      if @snikk.update_attributes(params[:snikk])
        format.html { redirect_to(@snikk, :notice => 'Snikk was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @snikk.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /snikks/1
  # DELETE /snikks/1.xml
  def destroy
    @snikk = Snikk.find(params[:id])
    @snikk.destroy

    respond_to do |format|
      format.html { redirect_to(snikks_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Return a title on a per-page basis.
  def title
    base_title = "Snikkit"
    if @title.nil?
      base_title
    else
      "#{@title} | #{base_title}"
    end
  end  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/snikks_helper.rb
module SnikksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1>Snikk.it</h1>
  <%= image_tag("snikkit.png", :alt => "Snikkit", :class => "logo") %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", '/' %></li>
      <li><%= link_to "Help", '/help' %></li>
      <li><%= link_to "About", '/about' %></li>
      <li><%= link_to "Sign up", '/sign-up#' %></li>
      <li><%= link_to "Sign in", '/sign-in#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= stylesheet_link_tag 'snikkit' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div class="container">
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Listing microposts</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Url</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @microposts.each do |micropost| %>
  <tr>
    <td><%= micropost.content %></td>
    <td><%= micropost.url %></td>
    <td><%= micropost.user_id %></td>
    <td><%= link_to 'Show', micropost %></td>
    <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
    <td><%= link_to 'Destroy', micropost, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Micropost', new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @micropost.content %>
</p>

<p>
  <b>Url:</b>
  <%= @micropost.url %>
</p>

<p>
  <b>User:</b>
  <%= @micropost.user_id %>
</p>


<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<p>Awesome! Yay! Snikks!</p>

app/views/snikks/_form.html.erb
<%= form_for(@snikk) do |f| %>
  <% if @snikk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snikk.errors.count, "error") %> prohibited this snikk from being saved:</h2>

      <ul>
      <% @snikk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snikks/edit.html.erb
<h1>Editing snikk</h1>

<%= render 'form' %>

<%= link_to 'Show', @snikk %> |
<%= link_to 'Back', snikks_path %>

app/views/snikks/index.html.erb
<h1>Listing snikks</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Url</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @snikks.each do |snikk| %>
  <tr>
    <td><%= snikk.content %></td>
    <td><%= snikk.url %></td>
    <td><%= snikk.user_id %></td>
    <td><%= link_to 'Show', snikk %></td>
    <td><%= link_to 'Edit', edit_snikk_path(snikk) %></td>
    <td><%= link_to 'Destroy', snikk, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Snikk', new_snikk_path %>

app/views/snikks/new.html.erb
<h1>New snikk</h1>

<%= render 'form' %>

<%= link_to 'Back', snikks_path %>

app/views/snikks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @snikk.content %>
</p>

<p>
  <b>Url:</b>
  <%= @snikk.url %>
</p>

<p>
  <b>User:</b>
  <%= @snikk.user_id %>
</p>


<%= link_to 'Edit', edit_snikk_path(@snikk) %> |
<%= link_to 'Back', snikks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>